Bump onnxruntime-web from 1.18.0 to 1.19.2 (#445)
Bumps [onnxruntime-web](https://github.com/Microsoft/onnxruntime) from 1.18.0 to 1.19.2.
- [Release notes](https://github.com/Microsoft/onnxruntime/releases)
- [Changelog](https://github.com/microsoft/onnxruntime/blob/main/docs/ReleaseManagement.md)
- [Commits](https://github.com/Microsoft/onnxruntime/compare/v1.18.0...v1.19.2)

---
updated-dependencies:
- dependency-name: onnxruntime-web
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Other changes:

* Update package.json

Extension breaks, though:
```
ReferenceError: document is not defined
    at packed.js:2:622800
    at packed.js:2:623034
    at background.js:5:5
```

* Use CDN for .wasm binaries

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>