[tests] fix failing CI: `textAnalytics.js Negative` (#340)
Fixes the error:

  1) textAnalytics
    Negative:
  Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/inclusive-code-reviews-browser/inclusive-code-reviews-browser/test/textAnalytics.js)

It appears that the onnxruntime is slow on the first call.

I added a method to explicitly initialize and made this the first test
with a timeout.

I also reverted dependabot changes, which appear to cause this issue.

This reverts commit d1a96fa3ab36b2238236e1d4221d306bd0002588.

* Revert "Bump onnxruntime-web from 1.16.3 to 1.17.0 (#336)"

This reverts commit 9773102769501949b0d5f7024bac59f088159a4c.

* Revert "Bump onnxruntime-node from 1.16.3 to 1.17.0 (#337)"

This reverts commit 5455a2873d759f38669fab1d4adb259a8a32157e.