Update package.json
Extension breaks, though:
```
ReferenceError: document is not defined
    at packed.js:2:622800
    at packed.js:2:623034
    at background.js:5:5
```